version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
    volumes:
      - "./nginx/:/etc/nginx/templates/"
      - "${VOLUME_WORDPRESS_PATH}:/var/www/html:rw,cached"
      - "${VOLUME_LOCAL_PLUGINS_PATH}:/var/www/html/local-plugins"
      - "${VOLUME_LOCAL_THEMES_PATH}:/var/www/html/local-themes"
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${LOCAL_DOMAIN}"
      - "MULTISITE=${MULTISITE:-0}"
    depends_on:
      - wordpress
    restart: always

  mysql:
    image: mariadb:10.7
    container_name: ${APP_NAME}-mysql
    command: --lower_case_table_names=2
    volumes:
       - './data/db:/var/lib/mysql:delegated'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - '3306:3306'

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-wordpress
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - "${VOLUME_WORDPRESS_PATH}:/var/www/html:rw,cached"
      - "${VOLUME_LOCAL_PLUGINS_PATH}:/var/www/html/local-plugins"
      - "${VOLUME_LOCAL_THEMES_PATH}:/var/www/html/local-themes"
    depends_on:
      - mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - '8082:80'
    links:
      - mysql:mysql

  mailhog:
    container_name: ${APP_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  composer:
    image: composer
    container_name: ${APP_NAME}-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - "${VOLUME_WORDPRESS_PATH}:/var/www/html:rw,cached"
      - "${VOLUME_LOCAL_PLUGINS_PATH}:/var/www/html/local-plugins"
      - "${VOLUME_LOCAL_THEMES_PATH}:/var/www/html/local-themes"
